#pragma config(Sensor, in1,    armPo,          sensorPotentiometer)
#pragma config(Motor,  port2,           BL,            tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           FL,            tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           TLArms,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           TRArms,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BArms,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Claws,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BR,            tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)


//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define STOP 0
#define FORWARDS 1
#define BACKWARDS 2
#define TURNLEFT 3
#define TURNRIGHT 4
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//Drive function for the autonomous section
void drive(int direction){
	int speed = 100;
	if(direction == 1){
		//forwards
		motor[FL] = -speed;
		motor[FR] = speed;
		motor[BL] = speed;
		motor[BR] = -speed;
	}else if(direction == 2){
		//backwards
		motor[FL] = speed;
		motor[FR] = -speed;
		motor[BL] = -speed;
		motor[BR] = speed;
	}else if(direction == 3){
		//turn left
	  motor[FL] = speed;
		motor[FR] = speed;
		motor[BL] = -speed;
		motor[BR] = -speed;
	}else if(direction == 4){
		//turn right
		motor[FL] = -speed;
		motor[FR] = -speed;
		motor[BL] = speed;
		motor[BR] = speed;
	}else{
		//stop
	  speed = 0;
		motor[FL] = speed;
		motor[FR] = speed;
		motor[BL] = speed;
		motor[BR] = speed;
	}
}

//void off {
	//	motor[FL] = 0;
	//	motor[FR] = 0;
	//	motor[BL] = 0;
	//	motor[BR] = 0;
//}

//float getDesiredClawPos(){
//	float min = 1600;
//	if(SensorValue(armPo) < min)return -1;
//	float percent = armPo - min;
//	float max = 2900-min;
//	percent = percent/max;
//	return (percent > 1) ? 1 : percent;
//}

void clawclose(int power){
	motor[Claws] = -power;
}
void clawopen(int power){
	motor[Claws] = power;
}
void liftup(int power){
	motor[BArms] = power;
}
void liftdown(int power){
	motor[BArms] = -power;
}

//autonomous code here
task autonomous()
{
	drive(FORWARDS);
	wait1Msec(1000);
	drive(STOP);

	clawclose(127);
	wait1Msec(700);
	clawopen(0);

	drive(TURNRIGHT);
	wait1Msec(500);
	drive(STOP);

	drive(BACKWARDS);
	wait1Msec(1000);
	drive(STOP);

	slaveMotor(TLArms, BArms);
	slaveMotor(TRArms, BArms);
	while(SensorValue[armPo] <= 1700){
		liftup(127);
	}
	if(SensorValue[armPo] >= 1700){
		liftup(0);
	}
	if(SensorValue[armPo] > 1500){
		motor[Claws] = 127;
	}
	if(SensorValue[armPo] > 1700){
		motor[Claws] = 0;
		motor[BArms] = 0;
	}

	wait1Msec(200);
	while(SensorValue[armPo] <= 1700 && SensorValue[armPo] > 0){
		liftdown(127);
	}



}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//drive sub task
//called in the main task
task driveM()
{
	int deadzone = 20;
	while(true)
	{
		if(vexRT[Ch3] > deadzone || vexRT[Ch3] < -deadzone || vexRT[Ch1] > deadzone || vexRT[Ch1] < -deadzone)
		{
			motor[FL] = -vexRT[Ch3] - vexRT[Ch1];
			motor[BL] = vexRT[Ch3] + vexRT[Ch1];
			motor[FR] = vexRT[Ch3] - vexRT[Ch1];
			motor[BR] = -vexRT[Ch3] + vexRT[Ch1];
		}
		else
		{
			motor[FL] = motor[BL] = motor[FR] = motor[BR] = 0;
		}
	}
}


task usercontrol()
{
	//starts the seperate drive task, so as to avoid any lag issues
	startTask(driveM);
	//slaves all arm controls to the BArms name, all arm movements should happen at the same time
	slaveMotor(TLArms, BArms);
	slaveMotor(TRArms, BArms);
	//float desiredPos = -1;
	int triggered = 0;
	while(true)
	{

		//main arm up down
		//armPo is the shaft encoder for the arms, values go from 0 to about 4000, actually allows 265 degrees of movement for the axle
		//up
		if((vexRT[Btn5U] || vexRT[Btn8D]) && SensorValue[armPo] < 2300 && triggered == 0){
			motor[BArms] = -127;
		}else if((vexRT[Btn7L] || vexRT[Btn8L]) && triggered == 0){
		//down
			motor[BArms] = 100;
		//}else if(triggered == 0 && SensorValue[armPo] > 150){
		//	motor[BArms] = 20;
		}else if(triggered == 0){
			motor[BArms] = 0;
	 	}

		//if(desiredPos == getDesiredClawPos() > -0.5){
		//	int curClawPos = 0;
		//	if(desiredPos > curClawPos == SensorValue[clawPo]){

		//	}
	 // }else

		//claw open and close
	  if((vexRT[Btn6D] || vexRT[Btn8U])){
			motor[Claws] = 80;
		}else if(vexRT[Btn6U] || vexRT[Btn8R]){
			motor[Claws] = -80;
		}
else{
			motor[Claws] = 0;
		}

		//auto throw over the fence
		if((vexRT[Btn7D] && SensorValue[armPo] < 1700) || triggered == 1)
		{
			triggered = 1;
			motor[BArms] = 127;
			if(SensorValue[armPo] > 1000){
				motor[Claws] = 127;
			}
			if(SensorValue[armPo] > 1700){
				motor[Claws] = 0;
				motor[BArms] = 0;
				triggered = 0;
			}
		}

		if(vexRT(Btn7U) == 1){
				motor[Claws] = 0;
			motor[BArms] = 0;
			triggered = 0;
			motor[FL] = 0;
			motor[BL] = 0;
			motor[FR] = 0;
			motor[BR] = 0;
	}

		if(vexRT[Btn8DXmtr2]){
			if(SensorValue[armPo] < 300){
				motor[BArms] = 40;
			}
			else if(SensorValue[armPo] > 275){
				motor[BArms] = 0;
			}
		}


	}
}
