#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           claws,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arms,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           xLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           xRight,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)


//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;



	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	int speed = 100 ;

	motor[frontLeft] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = -speed;
	motor[backRight] = -speed;
	motor[xLeft] = 100;
	motor[xRight] = -100;
	wait1Msec(3000);
	speed = 0;
	motor[frontLeft] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = -speed;
	motor[backRight] = -speed;

	wait1Msec(2000);
	motor[xLeft] = 0;
	motor[xRight] = 0;

	motor[arms] = -100;
	wait1Msec(1000);
	motor[arms] = 0;

	motor[claws] = -100;
	wait1Msec(1000);
	motor[claws] = 0;

	motor[arms] = 100;
	wait1Msec(1000);
	motor[arms] = 0;

	speed = 100;
	motor[frontLeft] = -speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[backRight] = speed;
	wait1Msec(1000);
	speed = 0;
	motor[frontLeft] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = -speed;
	motor[backRight] = -speed;


	motor[arms] = 100;
	wait1msec(1000);
	motor[arms]  = 0;

	speed = 100;
	motor[frontLeft] = speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[backRight] = -speed;
	wait1msec(1000);
	speed = 0;
	motor[frontLeft] = -speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[backRight] = speed;

	speed = 100;
	motor[frontLeft] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = -speed;
	motor[backRight] = -speed;
	wait1msec(1000);
	speed = 0;
	motor[frontLeft] = -speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[backRight] = speed;

	speed = 100;
	motor[frontLeft] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = -speed;
	motor[backRight] = -speed;
	wait1msec(7000);
	speed = 0;
	motor[frontLeft] = -speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[backRight] = speed;


}


//drive sub task
//called in the main task
task driveM()
{
	int deadzone = 20;
	while(true)
	{
		if(vexRT[Ch3Xmtr2] > deadzone || vexRT[Ch3Xmtr2] < -(deadzone) || vexRT[Ch4Xmtr2] > deadzone || vexRT[Ch4Xmtr2] < -(deadzone)){

			if(vexRT[Ch3Xmtr2] > deadzone || vexRT[Ch3Xmtr2] < -(deadzone)){
	  		motor[frontLeft] = vexRT[Ch3Xmtr2];
	  		motor[backLeft] = vexRT[Ch3Xmtr2];
	  		motor[frontRight] = -(vexRT[Ch3Xmtr2]);
	  		motor[backRight] = -(vexRT[Ch3Xmtr2]);
	  	}

	  	if(vexRT[Ch4Xmtr2] > deadzone || vexRT[Ch4Xmtr2] < -deadzone){
	  		motor[frontLeft] += vexRT[Ch4Xmtr2];
	  		motor[backLeft] += vexRT[Ch4Xmtr2];
	  		motor[frontRight] += vexRT[Ch4Xmtr2];
	  		motor[backRight] += vexRT[Ch4Xmtr2];
	  	}

	  }else{
	  	motor[frontLeft] = motor[backLeft] = motor[frontRight] = motor[backRight] = 0;
	  }
	}
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

  int deadzone = 20;
	int xLeftS = 110;
	int xRightS = 100;

	int clawSpeed = 100;

	startTask(driveM);
	while(true){


	//claw and arm rotation
	  if(vexRT[Ch2] > deadzone || vexRT[Ch2] < -(deadzone)){
	  	motor[arms] = (vexRT[Ch2]/1.75);
	  }else{
	  	motor[arms] = 0;
	  }

	  //claw open close
	  //open
	  if(vexRT[Btn6U]){
	  	motor[claws] = clawSpeed;
	  //close
	  } else if(vexRT[Btn5U]){
	  	motor[claws] = -clawSpeed;
	  }else{
	  	motor[claws] = 0;
	  }

		//scissor lift controls
		if(vexRT[Btn7U]) {
			motor[xRight] = -xRightS;
			motor[xLeft] = xLeftS;
		} else if(vexRT[Btn7D] ) {
			motor[xRight] = xRightS;
			motor   [xLeft] = -xLeftS;
		} else if(vexRT[Btn7L]) {
			motor[xLeft] = xLeftS;
		} else if(vexRT[Btn7R]) {
			motor[xRight] = -xRightS;
		} else {
			motor[xLeft] = 0;
			motor[xRight] = 0;
		}
	}
}
