#pragma config(Motor,  port1,           frontRight,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           forkLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           forkRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           xLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           xRight,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

if(vexRT[Btn7U] ) {

motor[forkLeft] = 65;
motor[forkRight] = -65;
wait1Msec (2000);

}


}
