#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           forkLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           forkRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           xLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           xRight,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int xL = 100;
	int xR = 100;
	while(true)
	{


		//processJoysticks();
		motor[frontLeft] = vexRT[Ch3];
	  motor[backLeft] = vexRT[Ch3];

	  motor[frontRight] = vexRT[Ch3];
	  motor[backRight] = vexRT[Ch3];

	  motor[frontLeft] =+ vexRT[Ch1];
	  motor[backLeft] =+ vexRT[Ch1];

	  motor[frontRight] =+ -vexRT[Ch1];
	  motor[backRight] =+ -vexRT[Ch1];

	  //adjusts the speeds of the scissor lift motors
	  if(vexRT[Btn8D]) xL = xL + 5;

		if(vexRT[Btn8R]) xR = xR + 5;

	  if(vexRT[Btn8L]) xL = xL - 5;

		if(vexRT[Btn8U]) xR = xR - 5;

		if(vexRT[Btn6U]){
			xL = 100;
			xR = 100;
		}

		/** lifts forklift */
		if(vexRT[Btn7U] == 1 ) {
			motor[forkLeft] = 100;
			motor[forkRight] = -100;
			//motor[forkLeft] = motor[forkRight] = 0;
		}
		else if(vexRT[Btn7R] == 1) {
			motor[forkLeft] = -50;
			motor[forkRight] = 50;
			//motor[forkLeft] = motor[forkRight] = 0;
		}
		else{
			motor[forkLeft] = 0;
			motor[forkRight] = 0;
		}

		if(vexRT[Btn7L] == 1) {
			motor[xLeft] = -xL;
			motor[xRight] = xR;

		}
		else if(vexRT[Btn7D] == 1) {
			motor[xLeft] = xL;
			motor[xRight] = -xR;

		}else{
		  motor[xLeft] = 0;
		  motor[xRight] = 0;
	  }
	}
}
